DROP TABLE tickets;
DROP TABLE customers;
DROP TABLE films;

CREATE TABLE Customers(
id SERIAL4 PRIMARY KEY,
name VARCHAR(255),
funds INT4
);

CREATE TABLE Films(
id SERIAL4 PRIMARY KEY,
title VARCHAR(255),
price INT4
);

CREATE TABLE Tickets(
id SERIAL4 PRIMARY KEY,
customer_id INT4 REFERENCES customers(id) ON DELETE CASCADE,
film_id INT4 REFERENCES films(id) ON DELETE CASCADE
);
